# Generated by Django 4.0.6 on 2022-08-13 13:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import ordens.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ordem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reclamacao', models.TextField()),
                ('imagem', models.ImageField(blank=True, null=True, upload_to=ordens.models.filePath)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordens', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
