# Generated by Django 4.0.6 on 2022-08-13 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordens', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordem',
            name='estado',
            field=models.CharField(choices=[('A', 'Aguardando'), ('F', 'Finalizado'), ('C', 'Cancelado'), ('E', 'Em Progresso')], default='E', max_length=1),
        ),
    ]
