# Generated by Django 4.0.6 on 2022-08-13 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordens', '0002_ordem_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordem',
            name='estado',
            field=models.CharField(choices=[('A', 'Aguardando'), ('F', 'Finalizado'), ('C', 'Cancelado'), ('E', 'Em Progresso')], default='A', max_length=1),
        ),
    ]
